# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  my-docker-env:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  static-analysis:
    executor: my-docker-env
    steps:
      - run: 'echo analyse!'
  security-checks:
    executor: my-docker-env
    steps:
      - run: 'echo looking at dependencies against OWASP'
  unit-tests:
    executor: my-docker-env
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn clean
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test
  integration-tests:
    executor: my-docker-env
    steps:
      - run: "echo integration test!"
  build:
    executor: my-docker-env
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  dockerise-push:
    executor: my-docker-env
    steps:
      - run: 'echo dockerise!'
      - run: 'echo push to registry'
  deploy-to-dev:
    executor: my-docker-env
    steps:
      - run: 'echo deploying to dev!'
  deploy-to-int:
    executor: my-docker-env
    steps:
      - run: 'echo deploying to int!'
  e2e-tests:
    executor: my-docker-env
    steps:
      - run: 'echo running e2e tests!'
  deploy-to-stage:
    executor: my-docker-env
    steps:
      - run: 'echo deploying to stage!'
  deploy-to-prod:
    executor: my-docker-env
    steps:
      - run: 'echo deploying to prod!'

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - static-analysis
      - security-checks
      - unit-tests:
          requires:
            - static-analysis
            - security-checks
      - integration-tests:
          requires:
            - static-analysis
            - security-checks
      - build:
          requires:
            - unit-tests
            - integration-tests
          filters:
            branches:
                only: master
      - dockerise-push:
          requires:
            - build
      - deploy-to-dev:
          requires:
            - dockerise-push
      - deploy-to-int:
          requires:
            - deploy-to-dev
      - e2e-tests:
          requires:
            - deploy-to-int
      - approve-to-stage:
          type: approval
          requires:
            - e2e-tests
      - deploy-to-stage:
          requires:
            - approve-to-stage
      - approve-to-prod:
          type: approval
          requires:
            - deploy-to-stage
      - deploy-to-prod:
          requires:
            - approve-to-prod
