# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  static-analysis:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 'echo analyse!'
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn clean
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: "echo test!"
  dockerise-push:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 'echo dockerise!'
      - run: 'echo push to registry'
  deploy-to-dev:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 'echo deploying to dev!'
  deploy-to-int:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 'echo deploying to int!'
  deploy-to-stage:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: 'echo deploying to stage!'

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - static-analysis
      - build:
          requires:
            - static-analysis
      - test:
          requires:
            - build
      - dockerise-push:
          requires:
            - test
      - deploy-to-dev:
          requires:
            - dockerise-push
      - deploy-to-int:
          requires:
            - deploy-to-dev
      - deploy-to-stage:
          requires:
            - deploy-to-int
