apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reborn-service-discovery-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /sd
            backend:
              serviceName: reborn-service-discovery-service
              servicePort: 80
